raigad/src/main/java/com/netflix/raigad/monitoring/AllCircuitBreakerStatsMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/FsStatsMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/HttpStatsMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/JvmStatsMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/NetworkStatsMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/NodeIndicesStatsMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/OsStatsMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/ProcessStatsMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/SnapshotBackupMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/ThreadPoolStatsMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/TransportStatsMonitor.java

Fixed the bug related to calculating delta and removed resetStats which is not needed.

Fixing Monitor stats

---

raigad/src/main/java/com/netflix/raigad/defaultimpl/StandardTuner.java

Updating yml property to enable access to kibana from any endpoint

Updating Tuner so that kibana can be accessed from any endpoint

---

gradle.properties

Updating version in gradle.properties

Updating version

---

gradle.properties
raigad/src/main/java/com/netflix/raigad/monitoring/NodeIndicesStatsMonitor.java

Changing types of few servo monitors from Gauge to Counter and vice versa

Fixing Servo Monitor types

---

gradle.properties
raigad/src/main/java/com/netflix/raigad/configuration/RaigadConfigSource.java
raigad/src/main/java/com/netflix/raigad/configuration/RaigadConfiguration.java
raigad/src/main/java/com/netflix/raigad/monitoring/NodeIndicesStatsMonitor.java
raigad/src/main/resources/Raigad.properties

Updating configuration properties so that Environment properties and properties from file can be read correctly.
Updating calculation of Delta metrics related to IndexStats.

Updating configuration properties and monitoring metrics

---

build.gradle
gradle.properties
raigad/src/test/java/com/netflix/raigad/backup/TestBackupRestore.java
raigad/src/test/java/com/netflix/raigad/indexmanagement/TestIndexManagement.java
raigad/src/test/java/com/netflix/raigad/scheduler/TestScheduler.java

Upgrading libraries, fixing and temporarily commenting out couple of tests till we fix ThreadLeak errors

Upgrading libraries and fixing tests

---

gradle.properties
raigad/src/main/java/com/netflix/raigad/configuration/RaigadConfiguration.java
raigad/src/main/java/com/netflix/raigad/monitoring/FsStatsMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/HttpStatsMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/JvmStatsMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/NetworkStatsMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/NodeIndicesStatsMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/OsStatsMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/ProcessStatsMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/SnapshotBackupMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/ThreadPoolStatsMonitor.java
raigad/src/main/java/com/netflix/raigad/monitoring/TransportStatsMonitor.java
raigad/src/main/resources/Raigad.properties

Backporting changes from 1.4.1 to 1.3.2 which fix configurations and monitors

Backporting changes from 1.4.1 to 1.3.2 which fix configurations and monitors

---

build.gradle
raigad-es-extensions/src/main/java/org/elasticsearch/discovery/custom/CustomDiscovery.java

Upgrading ES Version from 1.4.1 to 1.5.0
Added new parameter in constructor for ZenDiscovery

Upgrading to ES Version 1.5.0

---

gradle.properties

Updating new version in gradle.properties

Updating new version

---

gradle.properties
raigad/src/main/java/com/netflix/raigad/configuration/IConfiguration.java
raigad/src/main/java/com/netflix/raigad/configuration/RaigadConfiguration.java
raigad/src/main/java/com/netflix/raigad/defaultimpl/StandardTuner.java

Adding configuration properties and tuning yaml for Multi-region Tribe node support

Adding configuration properties and tuning yaml for Multi-region Tribe node support

---

gradle.properties
raigad/src/test/java/com/netflix/raigad/configuration/FakeConfiguration.java

(cherry picked from commit e3f7c161fada5f8227bfc046b820253b0d9e0284)

Implementing new missing method in FakeConfiguration

---

gradle.properties
raigad/src/main/java/com/netflix/raigad/backup/RestoreBackupManager.java
raigad/src/main/java/com/netflix/raigad/backup/SnapshotBackupManager.java
raigad/src/main/java/com/netflix/raigad/identity/EurekaHostsSupplier.java
raigad/src/main/java/com/netflix/raigad/resources/ElasticsearchBackup.java

1) Added support for Restoring Indices with different names
2) Added new REST call for Restoring with rename option
3) Fixing the handling of commaSeparatedIndices in SnapshotBackup

Adding support for Restoring Indices with different names and other changes

---

raigad/src/test/java/com/netflix/raigad/backup/TestBackupRestore.java

Fixing the Restore test

---

gradle.properties
raigad-es-extensions/src/main/java/org/elasticsearch/discovery/custom/CustomUnicastHostsProvider.java
raigad/src/main/java/com/netflix/raigad/backup/RestoreBackupManager.java
raigad/src/main/java/com/netflix/raigad/backup/SnapshotBackupManager.java
raigad/src/main/java/com/netflix/raigad/identity/InstanceManager.java
raigad/src/main/java/com/netflix/raigad/resources/ElasticsearchConfig.java
raigad/src/main/java/com/netflix/raigad/utils/TribeUtils.java

1) Fixed a bug in RestoreManager 
2) Updated Unicast Host Provider to correctly add related nodes for Tribe Setup

Adding fixes to RestoreProcess and Tribe Setup

---

gradle.properties
raigad/src/test/java/com/netflix/raigad/resources/TestElasticsearchConfig.java

Fixing test and upgrading the version to ES 1.5.2

Fixing test and upgrading the version to ES 1.5.2

---

gradle.properties
raigad/src/main/java/com/netflix/raigad/aws/AWSMembership.java
raigad/src/main/java/com/netflix/raigad/aws/UpdateTribeSecuritySettings.java
raigad/src/main/java/com/netflix/raigad/configuration/IConfiguration.java
raigad/src/main/java/com/netflix/raigad/configuration/RaigadConfiguration.java
raigad/src/main/java/com/netflix/raigad/defaultimpl/StandardTuner.java
raigad/src/main/java/com/netflix/raigad/identity/IMembership.java
raigad/src/test/java/com/netflix/raigad/configuration/FakeConfiguration.java

1) Adding new property for Tribe Node Setup to resolve index conflicts
2) Adding new method to getPorts for mentioned ACL. Fixing the logic to remove and add new acls during Security Group updates

Updates to Tribe Node Setup

---

gradle.properties
raigad/src/main/java/com/netflix/raigad/configuration/RaigadConfiguration.java

Order of reading properties will be as follows:
-- Default Parameters
-- If any of the parameters is provided using Properties file or as part of System properties then, value of the parameter overrides default params

Fixing configuration parameters

---

build.gradle
gradle.properties

Updating aws-java-sdk to latest.release

Updating aws-java-sdk to latest

---

gradle.properties
raigad/src/main/java/com/netflix/raigad/aws/AWSMembership.java
raigad/src/main/java/com/netflix/raigad/aws/UpdateVPCSecuritySettings.java
raigad/src/main/java/com/netflix/raigad/configuration/IConfiguration.java
raigad/src/main/java/com/netflix/raigad/configuration/RaigadConfiguration.java
raigad/src/main/java/com/netflix/raigad/identity/IMembership.java
raigad/src/main/java/com/netflix/raigad/startup/RaigadServer.java
raigad/src/main/java/com/netflix/raigad/utils/SystemUtils.java
raigad/src/test/java/com/netflix/raigad/configuration/FakeConfiguration.java

1) Added Configuration properties for instance in VPC mode and for instance in VPC Migration mode
2) Added a check to find if an instance is deployed in VPC
3) Added new file for Updating Security Group deployed in VPC

Adding changes to make Raigad work in VPC and also during VPC Migration

---

gradle.properties

Upgrading to later version in gradle.properties

Upgrading to later version

---

build.gradle
gradle.properties
raigad-discovery-plugin/build.gradle
raigad-discovery-plugin/src/main/resources/plugin-metadata/plugin-descriptor.properties
raigad/src/main/java/com/netflix/raigad/utils/TribeUtils.java
raigad/src/test/java/com/netflix/raigad/backup/TestBackupRestore.java
raigad/src/test/java/com/netflix/raigad/configuration/UnitTestModule.java
raigad/src/test/java/com/netflix/raigad/dataobjects/TestMasterNodeInfoMapper.java
raigad/src/test/java/com/netflix/raigad/defaultimpl/TestElasticsearchProcessManager.java
raigad/src/test/java/com/netflix/raigad/defaultimpl/TestStandardTuner.java
raigad/src/test/java/com/netflix/raigad/indexmanagement/TestIndexManagement.java
raigad/src/test/java/com/netflix/raigad/resources/TestElasticsearchConfig.java
raigad/src/test/java/com/netflix/raigad/utils/FakeSleeper.java
raigad/src/test/java/com/netflix/raigad/utils/TestElasticsearchUtils.java

- Updating Elasticsearch to 2.4.4
- Updating test dependencies
- Updating versioning to be consistent with Elasticsearch

Updating Elasticsearch to 2.4.4

---

build.gradle
gradle.properties
raigad/src/main/java/com/netflix/raigad/configuration/IConfiguration.java
raigad/src/main/java/com/netflix/raigad/configuration/RaigadConfiguration.java
raigad/src/main/java/com/netflix/raigad/defaultimpl/StandardTuner.java
raigad/src/test/java/com/netflix/raigad/configuration/FakeConfiguration.java

Introducing a notion of stack to determine node role (master, data, or search); bumping ES version to 5.4.0.

Adding stack for node role configuration; bumping ES version to 5.4.0
